name: Testing Approval
on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: | # Approve this PR
        curl --request POST
          --url https://api.github.com/repos/${{github.repository}}
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
          --header 'content-type: application/json' \
          -d '{"event": "APPROVE"}'
       